#!/bin/bash

echo "dofile(\"game/actors/$1/$1.lua\")" >> actors.lua
mkdir $1
touch $1/animation.lua
echo "dofile(\"game/actors/$1/animation.lua\")" > $1/$1.lua
(cat <<EOF
animations.$1 = animation.build_set(get_bitmap("game/actors/$1/$1.pcx"), 0, 0)
animations.$1.anims.stand = {
    {
	duration = 0,
	frame = 0
    }
}

animations.$1.anims.walk = {
    {
	duration = 0,
	frame = 0
    }
}
EOF
) >> $1/animation.lua

(cat <<EOF

actors.$1 = {
        id = "$1",
        name = "$1",
        pos = {x = 0, y = 0},
        color = 255000,
        speed = 150,
        inventory = {},
        flipped = false,
        aplay = animation.start(animations.$1, "stand")
}
EOF
) >> $1/$1.lua
