-- load the engine
dofile("scripts/environment.lua")
dofile("scripts/library.lua")
dofile("scripts/debug.lua")
dofile("scripts/repl.lua")
dofile("scripts/event.lua")
dofile("scripts/engine.lua")
dofile("scripts/clock.lua")
dofile("scripts/tasks.lua")
dofile("scripts/animation.lua")
dofile("scripts/actors.lua")
dofile("scripts/rooms.lua")
dofile("scripts/game.lua")
dofile("scripts/dialogue.lua")
dofile("scripts/filesystem.lua")

-- load the game
dofile("game/actors/actors.lua")
dofile("game/dialogue/dialogue.lua")
dofile("game/items/items.lua")