-- this file is procedurally generated by utils/build_costume.py
-- so you probably shouldn't edit it by hand :)

require "src/game/costume"

local cost, anim, deck, curve

-- art/car
--------------------------------------------------

cost = Costume.new()
cost:addPose("idle", 5, "game/costumes/car/idle.png", 1, 160, 58, true)
cost:addPose("open", 5, "game/costumes/car/open.png", 1, 160, 58, false)
costumes.car = cost

-- art/bonson
--------------------------------------------------

cost = Costume.new()
cost:addPose("idle", 5, "game/costumes/bonson/idle.png", 1, 52, 97, true)
costumes.bonson = cost

-- art/leon
--------------------------------------------------

cost = Costume.new()
cost:addPose("idle", 5, "game/costumes/leon/idle.png", 1, 52, 102, true)
costumes.leon = cost

-- art/santino
--------------------------------------------------

cost = Costume.new()
cost:addPose("idle", 5, "game/costumes/santino/idle.png", 24, 40, 60, true)
cost:addPose("talk", 5, "game/costumes/santino/talk.png", 24, 40, 60, true)
cost:addPose("walk", 8, "game/costumes/santino/walk8.png", 24, 40, 60, true)
cost:addPose("walk", 2, "game/costumes/santino/walk2.png", 24, 40, 60, true)
cost:addPose("walk", 4, "game/costumes/santino/walk4.png", 24, 40, 60, true)
cost:addPose("walk", 6, "game/costumes/santino/walk6.png", 24, 40, 60, true)
costumes.santino = cost

-- art/taag
--------------------------------------------------

cost = Costume.new()
cost:addPose("idle", 5, "game/costumes/taag/idle.png", 1, 48, 97, true)
costumes.taag = cost

-- art/charles
--------------------------------------------------

cost = Costume.new()
cost:addPose("idle", 5, "game/costumes/charles/idle.png", 1, 51, 103, true)
costumes.charles = cost

-- art/andreja
--------------------------------------------------

cost = Costume.new()
cost:addPose("idle", 5, "game/costumes/andreja/idle.png", 1, 66, 97, true)
costumes.andreja = cost

